name: Bale Post Tracker

on:
  schedule:
    # این دستور باعث می‌شود کد هر یک ساعت یک‌بار اجرا شود
    - cron: '0 * * * *'
  workflow_dispatch:
    # این گزینه به شما اجازه می‌دهد تا به صورت دستی هم کد را اجرا کنید

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # کد پروژه شما را دانلود می‌کند
        uses: actions/checkout@v3

      - name: Set up Python
        # پایتون را آماده می‌کند
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        # کتابخانه‌های لازم برای اجرای کد را نصب می‌کند
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run the tracker script
        # کد اصلی پایتون را اجرا می‌کند و اطلاعات حساس را به آن می‌دهد
        env:
          BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
          BALE_CHAT_ID: ${{ secrets.BALE_CHAT_ID }}
          TRACKING_CODE: ${{ secrets.TRACKING_CODE }}
        run: python tracker.py

      - name: Commit and push if changed
        # اگر وضعیت مرسوله تغییر کرده باشد، فایل وضعیت جدید را ذخیره می‌کند
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add last_status.txt
          git commit -m "Update last tracking status" || exit 0
          git push
